Add scripts for Open-iAPS, this version for beta testers
loopandlearn/lnl-scripts pull request #45
Opened 2024-05-02 23:42 UTC by marionbarker

2024-05-03 18:50 UTC, bjorkert requested changes

2024-05-03 18:50 UTC, bjorkert commented on src/BuildOpen-iAPS.sh
> +        echo -e "      https://discord.gg/ptkk2Y264Z"
This is the iAPS discord, not Oi?

2024-05-03 22:56 UTC, marionbarker commented on src/BuildOpen-iAPS.sh
> +        echo -e "      https://discord.gg/ptkk2Y264Z"
updated. Thanks.

2024-05-04 09:17 UTC, bjorkert approved these changes

2024-05-04 11:58 UTC, MikePlante1 approved these changes
LGTM. Thanks!

2024-05-06 20:22 UTC, marionbarker commented
Closing because the app was renamed.

2024-05-06 20:22 UTC, closed without merging